### ISSUE TITLE
 UNMET PEER DEPENDENCY

### ISSUE THREAD

**Issue by MedinaGitHub** [prettier/eslint-config-prettier#137]
![image](https://user-images.githubusercontent.com/16387514/74807746-f9bb6980-52c7-11ea-9da4-6ae2b0dda5e6.png)
 sorry, i have this problem. thanks you for your help

**Comment by j-f1** [comment]
`eslint-config-prettier` should be installed in the same location as ESLint itself.

**Comment by MedinaGitHub** [comment]
so eslint-config-prettier not working of globally way?

**Comment by lydell** [comment]
@MedinaGitHub Have you double-checked that `eslint` actually _is_ installed globally (in the same ”global space” if you’re using a Node.js version manager), because your `npm` does not seem to think so.

Btw, “UNMET PEER DEPENDENCY” is rarely the mistake of a package – it is up to the user to install peer dependencies themselves, that’s how peer dependencies work.

**Comment by MedinaGitHub** [comment]
![image](https://user-images.githubusercontent.com/16387514/74860586-ac6ee480-5327-11ea-81d6-9b5006772b51.png)

**Comment by lydell** [comment]
Well, eslint sure looks installed in that image at least.

However, I do notice one difference. In your first screenshot you use `sudo npm` but in the second you use just `npm`. Could that be why, maybe?

If you run these commands, does the issue occur again?

```
npm un -g eslint eslint-config-prettier
npm i -g eslint
npm i -g elsint-config-prettier
```

**Comment by MedinaGitHub** [comment]
npm un -g eslint eslint-config-prettier Run Ok
npm i -g eslint Run Ok
npm i -g elsint-config-prettier Fail

sudo is necessary, you know. 

about de sudo npm and only and in list -g --depth 0 the result is the same

![image](https://user-images.githubusercontent.com/16387514/74865541-083d6b80-5330-11ea-9aa2-3a1ba66250a6.png)

=(

**Comment by MedinaGitHub** [comment]
is required npm i -g eslint@3.14.1 ? because this neither work

**Comment by lydell** [comment]
3.14.1 or any later version is required.

I’m out of ideas now, sorry! If you manage to figure out what’s going on, feel free to post here.

**Comment by lydell** [comment]
Seems like peerDependencies are weird when installing globally:

- https://npm.community/t/npm-doesnt-find-peer-dependency-from-global-package/6771
- https://github.com/eslint/eslint/issues/9319
- https://github.com/npm/npm/issues/9857

But everyone seems to just close/ignore this issue.

**Comment by MedinaGitHub** [comment]
i will try with yarn, maybe it's npm error

**Comment by lydell** [comment]
You could just ignore the warning as well, couldn’t you?

**Comment by MedinaGitHub** [comment]
with --force ?

**Comment by lydell** [comment]
No, just ignore it in your head. Everything still works, right?

**Comment by jpickwell** [comment]
`eslint-config-prettier` did not fail to install just because you're "missing" a peer dependency. You can see it in the list of global packages in one of your earlier comments.

As was already mentioned, installing eslint, and its configs and plugins, should not be done globally as that doesn't make any sense since each project could have different version requirements. If you're doing this to try and save space on your storage drive, then look into [PNPM](https://pnpm.io/).

**Comment by k4y4k** [comment]
> sudo is necessary, you know.

Not with npm it's not. fix your permissions lol

**Comment by JounQin** [comment]
close due to inactive, maybe a reproduction repo would help of it still occurs.
