### ISSUE TITLE
Multi-line object functionality working?

### ISSUE THREAD

**Issue by GollyJer** [prettier/eslint-config-prettier#151]
Using vscode to run prettier with the ESLint extension...

Should it be possible to maintain prettier's [Multi-line objects](https://prettier.io/docs/en/rationale.html#multi-line-objects) functionality?

I can't seem to make it work (or any mulitline reformatting for that matter).
Curious if it is possible at all or I'm expecting something I shouldn't.

Thanks!
Jeremy

**Comment by lydell** [comment]
Hi!

This is an ESLint config that does nothing but turning a bunch of rules off. So I doubt your issue is due to a bug in this package!

Here’s a tip on how to debug:

1. Try with _only_ running Prettier _from the command line._ Do you get the expected output?
2. Then with _only ESLint_ (from the command line).
3. Then run them in sequence: Prettier, then ESLint. And ESLint, then Prettier.
4. If everything works from the command line, start testing from VSCode. Which plugins do you use? One for Prettier, one for ESLint? Try with only one enable first, then both. etc etc

**Comment by GollyJer** [comment]
Got it working. Thanks!!
