### ISSUE TITLE
Issue Prettier, eslint x codegen & @vue/apollo-composable

### ISSUE THREAD

**Issue by jlorezz** [prettier/eslint-config-prettier#188]
Currently, having an issue with GraphQL code gen and @vue/apollo-composable. ELINT and prettier is automatically formatting stuff to be wrong. 
```
export default defineComponent({
	name: 'userlist',
	setup() {
		// eslint-disable-next-line prettier/prettier
		const { onResult } = useQuery<GetUsersQueryVariables>(GetUsersDocument);

		onResult(({ data }) => {
			console.log(data);
		});

		return {
			people,
		};
	},
});
```

it automatically formats this part when i save:

``
const { onResult } = useQuery<GetUsersQueryVariables>(GetUsersDocument);
``

to this: 

``
const { onResult } = useQuery < GetUsersQueryVariables > GetUsersDocument;
``

which is not valid syntax for apollo-composable

**Comment by lydell** [comment]
Hi!

This happens when you use the “wrong” parser in Prettier. For example, when using the `babel` parser:

**Prettier 2.2.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAExPQEpxoCuANlgL6YC8mRacAikXAE4CeAPAOJwwCq9Fmias2ANQCGLAJYSARiUIA+ABQ9+gtABEIYIgFsEMAJQBuEABoQEAA4xp6ZKCksIAdwAKUhGmQgJJG4SbL5WciwSYADWvADKNpHSUADmyDAszFZw+nJwACZ5+QAyEilEEslwAGIQLPoSMPYpfhJEMBCWIAAWMPokAOpd0vBoCWBwsT7D0gBuw2x+YGihIEmCMB4RyfXIAGYB9FYAVmgAHgBCEdFxEoZFSXB7B3DHZ7FJyYpMEPBPJIcgBJCVh+OTyOAkTo2GSwfrSPIwLrIAAcAAYrNCIPR+hEbH5oYRWDNHlYAI5EH5wTa2XwoCRoAC0UDg+XynRYcHJ0g5mwqOyQ+3+LxA9H00jSGWFaA+XwpvwFzysMHkcIRSKQACYlRFpCQPgBhCD6fkgQgAVk6dDgABV5LTBQCZswAJJQQqwWJgGR2ACCbtiMDYij+9HI5CAA)

```sh
--parser babel
```

**Input:**

```jsx
const { onResult } = useQuery<GetUsersQueryVariables>(GetUsersDocument);
```

**Output:**

```jsx
const { onResult } = useQuery < GetUsersQueryVariables > GetUsersDocument;

```

When using for example the `typescript` parser it looks like you expect:

**Prettier 2.2.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAExPQEpxoCuANlgL6YC8mRacAikXAE4CeAPAOJwwCq9Fmias2ANQCGLAJYSARiUIA+ABQ9+gtABEIYIgFsEMAJQBuEABoQEAA4xp6ZKCksIAdwAKUhGmQgJJG4SbL5WciwSYADWvADKNpHSUADmyDAszFZw+nJwACZ5+QAyEilEEslwAGIQLPoSMPYpfhJEMBCWIAAWMPokAOpd0vBoCWBwsT7D0gBuw2x+YGihIEmCMB4RyfXIAGYB9FYAVmgAHgBCEdFxEoZFSXB7B3DHZ7FJyYpMEPBPJIcgBJCVh+GBsGyEMAyOydGwyWD9aR5GBdZAADgADFY4RB6P0IjY-HDCKwZo8rABHIg-OCbWy+FASNAAWigcHy+U6LDgVOk3M2FR2SH2-xeIHo+mkaQyYrQHy+1N+wueVhg8kRyNRSAATKqItISB8AMIQfRCkCEACsnTocAAKvIGSKATNmABJKCFWCxKHSOwAQU9sTBij+9HI5CAA)

```sh
--parser typescript
```

**Input:**

```tsx
const { onResult } = useQuery<GetUsersQueryVariables>(GetUsersDocument);
```

**Output:**

```tsx
const { onResult } = useQuery<GetUsersQueryVariables>(GetUsersDocument);

```

The reason this happens is that when interpreted as JavaScript, the code happens to be valid syntax using the `<` and `>` operators (although the code is non-sensical), but when interpreted as TypeScript the code is a function call with a generic.

This issue often happens when people add `"parser": "whatever"` to their .prettierrc. If so, the solution is to remove that. See https://prettier.io/docs/en/configuration.html#setting-the-parserdocsenoptionshtmlparser-option for more information.

Hopefully that’s the problem. Otherwise it’s hard to say what’s wrong since you didn’t include steps to reproduce. A tip for the future: Try running _only_ Prettier when debugging stuff like this. Then you can find out if it’s Prettier’s fault, ESLint’s fault or the combination of the two, and find the correct repo to report in. I doubt this has anything to do with eslint-config-prettier.

**Comment by lydell** [comment]
Closing because no response.
