### ISSUE TITLE
Prettier tries to add space around union type separator

### ISSUE THREAD

**Issue by simPod** [prettier/eslint-config-prettier#202]
In #164 the `@typescript-eslint/space-infix-ops` rule was disabled. But prettier still tries to add spaces around union separator in my ts types:

```diff
interface I {
-  a: string|number;
+  b: string | number;
}
```

Is that a bug or intended behaviour and is there a way to disable it?

**Comment by lydell** [comment]
Hi! Prettier works the way it does and generally cannot be configured. This config turns off all ESLint rules that disagree with Prettier’s formatting, letting Prettier decide (since it cannot be configured). So this is working as intended from the point of view of eslint-config-prettier.

If you _really_ care about those spaces not being there, you could try [prettier-eslint](https://github.com/prettier/prettier-eslint), though I wouldn’t recommend it.

**Comment by simPod** [comment]
Thank you for response. So the rule is disabled and the behaviour is then hardcoded in prettier -> resulting in spaces being added?

And why wouldn't you recommend it?

**Comment by lydell** [comment]
> So the rule is disabled and the behaviour is then hardcoded in prettier -> resulting in spaces being added?

Correct!

> And why wouldn't you recommend it?

Because it’s slower and used to be a bit undermaintained. But feel free to try it!
