### ISSUE TITLE
is there a way to override all configuration?

### ISSUE THREAD

**Issue by xblurx** [prettier/eslint-config-prettier#213]
Hi
I was integrating `eslint-config-prettier` into a project, and ran into this issue:
Here is our current .eslintrc config (simpified) 
```
module.exports = {
...
extends: [
    ...some rules
    'prettier'
    ],

rules: {
    ...overrideEslintRules,
    }
}
``` 
if, to say, we're overriding an `indent` rule in `overrideEslintRules` to `[2, 4, { SwitchCase: 1 }]`, that would mean `eslint-config-prettier` 's disabling of `indent` does not work anymore 

The question is, is there any way to still override all of it with `eslint-config-prettier` ? Cause in `rules` we have so much rules that are often overlap with prettier, and disabling them manually renders `eslint-config-prettier` unnecessary. 
Thanks.

**Comment by lydell** [comment]
Hi!

Removing stuff from `rules` that is unnecessary or conflicts with Prettier is the way to go. Personally I’ve done exactly that in many projects, so that I ended up not needing eslint-config-prettier at all. I just run the [CLI helper tool](https://github.com/prettier/eslint-config-prettier/#cli-helper-tool) sometimes to check that I don’t have any conflicts.

**Comment by xblurx** [comment]
makes sense, thanks
