### ISSUE TITLE
autoFixOnSave alternates between correct and wrong indentation

### ISSUE THREAD

**Issue by dj-hedgehog** [prettier/eslint-config-prettier#37]
I have quite strange error. I set `eslint.autoFixOnSave` to `true`. When I save a file once it formats my code successfully:

![image](https://user-images.githubusercontent.com/7140800/33176185-7836f5fc-d05e-11e7-802b-083591a901c4.png)

When I save it again it messes up the indentation.

![image](https://user-images.githubusercontent.com/7140800/33176226-9d8798ca-d05e-11e7-864b-ba160f684dca.png)

When I save a 3rd time it fixes the indentation again as in screenshot 1 and so on.

How can this happen?
This is my `.eslintrc.json`:

```
{
  "extends": "prettier",
  "parserOptions": {
    "sourceType": "module",
    "ecmaVersion": 2017
  },
  "env": {
    "es6": true,
    "node": true
  },
  "plugins": [
    "prettier"
  ],
  "rules": {
    "prettier/prettier": [
      "error",
      {
        "semi": false,
        "printWidth": 120
      }
    ]
  }
}
```

*Edit:* I recorded a video with the strange behaviour:

![eslint-problem](https://user-images.githubusercontent.com/7140800/33177813-43a1a160-d064-11e7-82cb-9656dc78dc7d.gif)

**Comment by lydell** [comment]
You have at least five tools that could be the culprit:

- Prettier
- ESLint
- eslint-plugin-prettier
- eslint-config-prettier
- Your editor integration

When debugging these kinds of things, it's always better to try to reduce the problem.

- What happens if you run ESLint from the command line?
- What happens if you run Prettier from the command line?
- What happens if you simplify your ESLint config?
- Why do you think this problem has to do with eslint-config-prettier?

Also, if you'd like help debugging from others, it really helps if you post the problematic code as text, not just in a gif. Then people can copy-paste and try things out themselves. The absolutely best thing to do, is to create a minimal repo that reproduces the problem that people can clone.

**Comment by dj-hedgehog** [comment]
I found the error. The final culprit was *drumroll* the file `.vscode/settings.json` which a developer commited. It had formatOnSave() activated which collided with my global settings.
