### ISSUE TITLE
How to remove semi

### ISSUE THREAD

**Issue by dmy147** [prettier/eslint-config-prettier#38]
I dont like semi ,but it in default; 
When i want to add rule to ban semi , then i cant pass the check
```
{
  "parser": "babel-eslint",
  "parserOptions": {
    "sourceType": "module", 
    "allowImportExportEverywhere": true 
  },
  "extends": [
    "standard",    
    "eslint:recommended",
    "plugin:react/recommended",
    "standard-react",
    "prettier",
    "prettier/react",
    "prettier/standard"
  ], 
  "rules": {
    "semi":"error",
    "no-extra-semi":"error",
    "prettier/prettier": "error",
    "react/prop-types": 0 
  },
  "plugins": [
    "html",
    "react",
    "prettier",
    "standard"
  ]
}
```

![qq20171128-142646](https://user-images.githubusercontent.com/20147371/33305277-530d1cdc-d448-11e7-877a-e03b04e29a98.png)

**Comment by lydell** [comment]
The `semi` and `no-extra-semi` rules cause conflicts with Prettier, so you should not enable them.

What you want to do is setting _Prettier's_ [semi](https://prettier.io/docs/en/options.html#semicolons) option. Then, Prettier will remove or add all semicolons for you!

**Comment by dmy147** [comment]
THX
but I dont konw   how/where  to set  Prettier's semi option

**Comment by lydell** [comment]
You can either set the option directly in the eslint-plugin-prettier rule: https://github.com/prettier/eslint-plugin-prettier#options

Or you can use a Prettier config file: https://prettier.io/docs/en/configuration.html

I recommend using a Prettier config file, since it allows more editor integrations to understand what Prettier options you use.
