### ISSUE TITLE
List rules that are still enforced

### ISSUE THREAD

**Issue by tjallingt** [prettier/eslint-config-prettier#73]
Currently the readme contains a number of rules that are special cases with prettier and mentions that all "styling related lint rules" are disabled by this config.
However as a user of this config I'm interested in what the config is still error-ing on (in other words what kind of bugs/errors will be caught if i use this config?). Would it be possible to add a list of active rules to the readme or another file?

**Comment by tjallingt** [comment]
Another option would be to add uncommented lines for all still disabled rules in the js files or something.
I understand that this puts an unfortunate burden on the maintainers however so I'm not sure what is desirable here 😕

**Comment by j-f1** [comment]
This plugin doesn’t actually enable any rules — we just disable ones that conflict with Prettier.

**Comment by tjallingt** [comment]
Yes, I mentioning that in the issue...

My point is that users of this config will have a hard time finding out what rules are still enabled.

Or more specifically: I can't tell what linting rules are still active when using this config and I'd like to know.

Or am i misunderstanding and shouldn't people use this config directly and is this instead for other projects to extend?

**Comment by lydell** [comment]
@tjallingt ESLint allows use to extend multiple configs at once. The idea is to use any config you like and then eslint-config-prettier on top of that. All eslint-config-prettier does is disabling conflicting rules.

If you extend _only_ eslint-config-prettier that's equivalent extending no config at all, since all rules are off by default in ESLint.
